### ISSUE TITLE
USPS Not Working

### ISSUE THREAD

**Issue by insanerwayner** [proninyaroslav/libretrack#36]
I registered for the API and put in my username and company name to LibreTrack, but shouldn't  it also need the password?  

I am seeing no indication that is pulling any data from my account.

**Comment by wisetux** [comment]
Your API needs to have access to track requests. I just applied mine using steps below.

1. To obtain Package Tracking API (API=TrackV2) access, users will need to contact the USPS Web Tools Program Office to request access and supply additional information for customer verification.
        - Note: This applies to both TrackV2 API simplified track requests (i.e., “TrackRequest”) and TrackV2 API detailed track requests (i.e., “TrackFieldRequest”).
2. Users should follow these steps to submit a request for Tracking APIs access:
        - Navigate to: https://usps.force.com/emailus/s/web-tools-inquiry. Provide user name (Web Tools User ID), select “Tracking APIs”, select “Track API” and submit the request with the following information below in the “Additional Information” text box:
                • Web Tools UserID:
                • Mailer ID (MID):
                • Company Name:
                • Requester First and Last Name:
                • Requester Email:
                • Requester Phone number:
                • Mailing Address:
                • Mailing City:
                • Mailing State:
                • Mailing Zip Code:
                • PROD Registration Date:
                • API access requested: Package Tracking (API=TrackV2)
                • Anticipated volume:
                • Any additional information from the customer:

**Comment by proninyaroslav** [comment]
If you are still having problems, feel free to open it again.
