### ISSUE TITLE
Add icon.png to Fastlane en-US images

### ISSUE THREAD

**Issue by licaon-kter** [proninyaroslav/libretrack#45]

**Comment by proninyaroslav** [comment]
Added [5db2c91](https://github.com/proninyaroslav/libretrack/commit/5db2c91401a06023f1ddc35e11bb5deb5c032d88). Is it true that I can just remove the tag and set it to the current commit for the changes to show up in F-Droid?

**Comment by licaon-kter** [comment]
No, this version was published, nothing can be changed.
